### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by gtfierro** [gtfierro/mdal#5]
```
panic: capnp: address out of bounds

goroutine 121 [running]:
zombiezen.com/go/capnproto2.List.Struct(0xc4207329f0, 0x500000020, 0x200000000, 0xffffffffffffffff, 0x1, 0x5, 0x0, 0x0, 0x0, 0x0, ...)
        /home/gabe/go/src/zombiezen.com/go/capnproto2/list.go:220 +0x204
github.com/gtfierro/mdal/capnp.Stream_List.At(0xc4207329f0, 0x500000020, 0x200000000, 0xffffffffffffffff, 0x1, 0x5, 0x0, 0x0, 0x0, 0x0, ...)
        /home/gabe/go/src/github.com/gtfierro/mdal/capnp/data.capnp.go:95 +0xa9
main.(*Timeseries).AddAlignedStream(0xc4206d9620, 0x5, 0xc4201c0090, 0xc4201c00c0, 0x0, 0x1)
        /home/gabe/go/src/github.com/gtfierro/mdal/timeseries.go:132 +0x17b
main.(*btrdbClient).getWindow(0xc420150100, 0xc42074e860, 0x10, 0x10, 0x5, 0x2, 0x0, 0x0, 0xed222e21d, 0x198f4a0, ...)
        /home/gabe/go/src/github.com/gtfierro/mdal/timeseriesdb.go:320 +0xb33
main.(*btrdbClient).handleRequest(0xc420150100, 0xc42074e860, 0x10, 0x10, 0x5, 0x2, 0x0, 0x0, 0xed222e21d, 0x198f4a0, ...)
        /home/gabe/go/src/github.com/gtfierro/mdal/timeseriesdb.go:199 +0xcb
main.worker.start.func1(0xc42059e120, 0xc42059e180, 0xc420150100)
        /home/gabe/go/src/github.com/gtfierro/mdal/timeseriesjob.go:23 +0x98
created by main.worker.start
        /home/gabe/go/src/github.com/gtfierro/mdal/timeseriesjob.go:18 +0x53
```

**Comment by gtfierro** [comment]
This is caused when there are duplicate UUIDs in the composition key. I think it makes sense to accept this if that's what the user wants
